import type { Metadata } from "next";
import { Inter, Roboto_Condensed } from "next/font/google";
import "./globals.css";
import styles from "./layout.module.css";
import Image from "next/image";
import Marvel from "./components/svg/Marvel";
import Link from "next/link";

const robotoCondensed = Roboto_Condensed({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={robotoCondensed.className}>
        <header>
          <Link href="/" aria-label="Go to homepage">
            <Marvel />
          </Link>
        </header>
        {children}
        <footer>Data provided by Marvel. © 2014 Marvel</footer>
      </body>
    </html>
  );
}
